### ISSUE TITLE
Bossbar

### ISSUE THREAD

**Issue by Tuvqlu** [Theslowaja/BossBar#1]
No config

**Comment by Theslowaja** [comment]
What ? Hahaha

**Comment by Tuvqlu** [comment]
Crashes now

**Comment by Tuvqlu** [comment]
Hey I saw you in my stream thanks for watching :))

**Comment by Theslowaja** [comment]
can i see the error log?

**Comment by Tuvqlu** [comment]
![Uploading DB9848E2-4B42-4A2F-AF1C-C1C247B1E4E9.jpeg…]()

**Comment by Tuvqlu** [comment]
![F7BCA4F8-D6B8-4ABA-94F1-31E282ED9CB6](https://user-images.githubusercontent.com/98550458/168317487-91b8c24d-f806-40a7-8a16-df1495da8020.jpeg)
