### ISSUE TITLE
BossBar Errer

### ISSUE THREAD

**Issue by SiahRBLX** [Theslowaja/BossBar#5]
I've updated BossBar to the recent build  and while starting server i get this error...

[15:30:41.103] [Server thread/INFO]: Enabling BossBar v1
[15:30:41.103] [Server thread/CRITICAL]: Error: "Class "xenialdan\apibossbar\BossBar" not found" (EXCEPTION) in "plugins/BossBar/src/Theslowaja/BossBar/Loader" at line 16
--- Stack trace ---
  #0 pmsrc/src/plugin/PluginBase(137): Theslowaja\BossBar\Loader->onEnable()
  #1 pmsrc/src/plugin/PluginManager(445): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #2 pmsrc/src/Server(1386): pocketmine\plugin\PluginManager->enablePlugin(object Theslowaja\BossBar\Loader#98999)
  #3 pmsrc/src/Server(1012): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#24902)
  #4 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #5 pmsrc/src/PocketMine(327): pocketmine\server()
  #6 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by SiahRBLX** [comment]
Was using it as as Source file instead of ".phar"

**Comment by Theslowaja** [comment]
use apibossbar virion
